=== pypi-data/pypi-mirror-37/packages/basis-set-exchange/basis_set_exchange-0.5.4.tar.gz/basis_set_exchange-0.5.4/basis_set_exchange/schema/table-schema.json
{
    "$schema": "http://json-schema.org/draft-07/#",
    "name": "bse_table_basis_set",
    "version": "0.1",
    "url": "TODO",
    "description": "JSON for describing how a table-based basis set is composed",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "basis_set_name",
        "basis_set_family",
        "basis_set_description",
        "basis_set_revision_description",
        "basis_set_role",
        "basis_set_elements",
        "basis_set_auxiliaries"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "table" ]
                },
                "schema_version": {
                    "description": "Version of the BSE table basis set schema being used",
                    "type": "string"
                }
            }
        },
        "basis_set_name": {
            "description": "Common name for the basis set",
            "type": "string"
        },
        "basis_set_family": {
            "description": "Broad family that the basis set is from",
            "type": "string"
        },
        "basis_set_description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "basis_set_notes": {
            "description": "Any notes pertaining to this basis set",
            "type": "string"
        },
        "basis_set_revision_description": {
            "description": "Brief description of the difference between this revision and the last",
            "type": "string"
        },
        "basis_set_role": {
            "description": "Role that this basis plays in a calculation",
            "type": "string",
            "enum": [ "orbital", "rifit", "jkfit", "jfit" ]
        },
        "basis_set_auxiliaries": {
            "description": "Auxiliary basis sets (fitting, etc) and how their role with his basis",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "jfit" : { "type": "string" },
                "jkfit" : { "type": "string" },
                "rifit" : { "type": "string" }
            }
        },
        "basis_set_elements": {
            "description": "Data for the elements of the basis set",
            "type": "object",
            "additionalProperties": false,
            "patternProperties":   {
                "^\\d+$" : {
                    "description": "Data for a single element in the basis set",
                    "type": "object",
                    "additionalProperties": false,
                    "required": [ "element_entry" ],
                    "properties": {
                        "element_references": {
                            "description": "Citation/Reference information for this element",
                            "type": "array",
                            "minItems": 1,
                            "uniqueItems": true,
                            "items": {
                                "type": "string"
                            }
                        },
                        "element_entry": {
                            "description": "Elemental basis set for this element",
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== pypi-data/pypi-mirror-37/packages/basis-set-exchange/basis_set_exchange-0.5.4.tar.gz/basis_set_exchange-0.5.4/basis_set_exchange/data/5-21G.1.table.json
{
    "molssi_bse_schema": {
        "schema_type": "table",
        "schema_version": "0.1"
    },
    "basis_set_name": "5-21G",
    "basis_set_family": "pople",
    "basis_set_description": "5-21G valence double-zeta basis set",
    "basis_set_revision_description": "Curated",
    "basis_set_role": "orbital",
    "basis_set_auxiliaries": {},
    "basis_set_elements": {
        "3": {
            "element_entry": "pople/5-21G.0.element.json"
        },
        "4": {
            "element_entry": "pople/5-21G.0.element.json"
        }
    }
}
